on:
  workflow_dispatch:
    inputs:
      ACTIVE_API_URL:
        description: 'The URL of the scanner settings'
        default: 'https://demo-stable.nonamesec.com/active'
        required: false
        type: string
      ACTIVE_SEVERITY_THRESHOLD:
        description: build disturb on error level supported values [high , medium, low, info, none]
        default: none
        required: false
        type: choice
        options:
          - high
          - medium
          - low
          - info
          - none
      ACTIVE_TEST_SUITE_ID:
        description: The Test suite id to be scanned.
        default: addfbbda-3e27-470d-b80d-bec514e089aa
        required: true
        type: string
      ACTIVE_BASE_URL:
        description: The Base URL for the App.
        default: 'http://localhost:5002'
        required: false
        type: string
jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: run vampi
        run: docker compose up -d 
      
      - name: test vampi
        run: curl -k http://localhost:5002/

      - name: docker login
        uses: docker/login-action@v1
        with:
          registry: jfrog.cicd.nonamesec.com/noname-docker-release
          username: noname-demo-latest@nonamesecurity.com
          password: ${{ secrets.ACTIVE_REGISTRY_PASSWORD }}

      - name: security test
        run: |
          docker run \
          --pull always \
          jfrog.cicd.nonamesec.com/noname-docker-release/active-cli:$(curl -k ${{github.event.inputs.ACTIVE_API_URL}}/backend/version) \
          scan \
          --api-url=${{ github.event.inputs.ACTIVE_API_URL }} \
          --api-token=${{ secrets.ACTIVE_API_TOKEN }} \
          --test-suite-id=${{ github.event.inputs.ACTIVE_TEST_SUITE_ID }} \
          --severity-threshold=${{ github.event.inputs.ACTIVE_SEVERITY_THRESHOLD }} \
          --base-url=${{ github.event.inputs.ACTIVE_BASE_URL }}

  deploy:
    needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo Hello world
